### ISSUE TITLE
Call To Action Block - no field(s) to link

### ISSUE THREAD

**Issue by jsirish** [dynamic/dynamic-blocks#15]
Need to add a Linkable-esque feature to Call To Action block

**Comment by korthjp17** [comment]
I wonder if we just add the field to pull from sitetree for this? Then we could have another extension to block that field if we add Linkable??

**Comment by jsirish** [comment]
That's a good call - if we hard code the internal link, Linkable actually works well with it. Spiffs in Core were setup this way. Linkable just moves that SiteTreeDropdown to the links tab

**Comment by jsirish** [comment]
closed via #18
