### ISSUE TITLE
Linkable bug

### ISSUE THREAD

**Issue by korthjp17** [dynamic/dynamic-blocks#17]
Linkable on a block doesn't work by default. If we make a block for that specific area (ContentBlock vs ContentBlock_AfterContent.ss) then it will work. It seems to only be an internal link that's not working - external was working fine on Bioionix.

This happened with Bioionix, but I tried on Sargento which I haven't done much with the blocks yet and it doesn't seem to be working on there either.

Not sure exactly where to add this issue, but making a note of it.

**Comment by jsirish** [comment]
I think this should go away now that we've switched to sheadawson/silverstripe-linkable

**Comment by jsirish** [comment]
We can reopen if this becomes an issue down the road
